spring:
  application:
     name: spring_web_client
  cloud:
    config:
      #uri: ${SPRING_CONFIG_URI:http://127.0.0.1:8080}
      uri: http://127.0.0.1:8080
      enabled: true
server:
  port: 8081